
cd %1

.\bin\ocamlc.exe -a -I lib lib/camlp4/Camlp4_import.cmo lib/camlp4/Camlp4_config.cmo lib/camlp4/Camlp4.cmo -o lib/camlp4/camlp4lib.cma

.\bin\ocamlc.exe -a -I stdlib lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Top/Top.cmo  -o lib/camlp4/camlp4o.cma

.\bin\ocamlc.exe -a -I stdlib lib/camlp4/camlp4lib.cma -linkall  lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Top/Top.cmo  -o lib/camlp4/camlp4of.cma

.\bin\ocamlc.exe -a -I stdlib lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo  lib/camlp4/Camlp4Top/Rprint.cmo lib/camlp4/Camlp4Top/Top.cmo  -o lib/camlp4/camlp4r.cma

.\bin\ocamlc.exe -a -I stdlib lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Top/Rprint.cmo lib/camlp4/Camlp4Top/Top.cmo  -o lib/camlp4/camlp4rf.cma

.\bin\ocamlc.exe -a -I stdlib lib/camlp4/camlp4lib.cma -linkall  lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedQuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Top/Top.cmo  -o lib/camlp4/camlp4orf.cma

.\bin\ocamlc.exe -nostdlib -a -I stdlib lib/camlp4/Camlp4_import.cmo lib/camlp4/Camlp4_config.cmo lib/camlp4/Camlp4.cmo lib/camlp4/Camlp4Parsers/Camlp4AstLoader.cmo lib/camlp4/Camlp4Parsers/Camlp4DebugParser.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlOriginalQuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedQuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationExpander.cmo lib/camlp4/Camlp4Printers/Camlp4AstDumper.cmo lib/camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo lib/camlp4/Camlp4Printers/Camlp4NullDumper.cmo lib/camlp4/Camlp4Printers/Camlp4OCamlAstDumper.cmo lib/camlp4/Camlp4Printers/Camlp4OCamlPrinter.cmo lib/camlp4/Camlp4Printers/Camlp4OCamlRevisedPrinter.cmo lib/camlp4/Camlp4Filters/Camlp4AstLifter.cmo lib/camlp4/Camlp4Filters/Camlp4ExceptionTracer.cmo lib/camlp4/Camlp4Filters/Camlp4FoldGenerator.cmo lib/camlp4/Camlp4Filters/Camlp4LocationStripper.cmo lib/camlp4/Camlp4Filters/Camlp4MapGenerator.cmo lib/camlp4/Camlp4Filters/Camlp4MetaGenerator.cmo lib/camlp4/Camlp4Filters/Camlp4Profiler.cmo lib/camlp4/Camlp4Filters/Camlp4TrashRemover.cmo lib/camlp4/Camlp4Top.cmo -o lib/camlp4/camlp4fulllib.cma

.\bin\ocamlc.exe -a -I stdlib lib/camlp4/camlp4lib.cma -linkall  lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlOriginalQuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Top/Top.cmo  -o lib/camlp4/camlp4oof.cma

rem  camlp4fulllib.cma  camlp4o.cma	 camlp4oof.cma	camlp4r.cma
rem  camlp4lib.cma	   camlp4of.cma  camlp4orf.cma	camlp4rf.cma


.\bin\ocamlc.exe -custom dynlink.cma -g -I lib -I lib/stublibs -I otherlibs/dynlink -I lib -I lib/stublibs/camlp4/boot lib/camlp4/boot/Camlp4_import.cmo lib/camlp4/boot/Camlp4_config.cmo lib/camlp4/boot/Camlp4.cmo lib/camlp4/boot/camlp4boot.cmo -o bin/camlp4boot.exe

.\bin\ocamlc.exe -I otherlibs/dynlink dynlink.cma -I otherlibs/win32unix unix.cma -I lib -I lib/stublibs lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Bin.cmo -o bin/camlp4.exe

.\bin\ocamlc.exe -I otherlibs/dynlink dynlink.cma -I otherlibs/win32unix unix.cma -I lib -I lib/stublibs lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo lib/camlp4/Camlp4Bin.cmo -o bin/camlp4of.exe

.\bin\ocamlc.exe -I otherlibs/dynlink dynlink.cma -I otherlibs/win32unix unix.cma -I lib -I lib/stublibs lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo lib/camlp4/Camlp4Bin.cmo -o bin/camlp4rf.exe 

.\bin\ocamlc.exe -I otherlibs/dynlink dynlink.cma -I otherlibs/win32unix unix.cma -I lib -I lib/stublibs lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo lib/camlp4/Camlp4Bin.cmo -o bin/camlp4o.exe 

.\bin\ocamlc.exe -I otherlibs/dynlink dynlink.cma -I otherlibs/win32unix unix.cma -I lib -I lib/stublibs lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlOriginalQuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo  lib/camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo lib/camlp4/Camlp4Bin.cmo -o bin/camlp4oof.exe 

.\bin\ocamlc.exe -I otherlibs/dynlink dynlink.cma -I otherlibs/win32unix unix.cma -I lib -I lib/stublibs lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlParserParser.cmo lib/camlp4/Camlp4Parsers/Camlp4QuotationCommon.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedQuotationExpander.cmo lib/camlp4/Camlp4Parsers/Camlp4GrammarParser.cmo lib/camlp4/Camlp4Parsers/Camlp4MacroParser.cmo lib/camlp4/Camlp4Parsers/Camlp4ListComprehension.cmo lib/camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo lib/camlp4/Camlp4Bin.cmo -o bin/camlp4orf.exe 

.\bin\ocamlc.exe -I otherlibs/dynlink dynlink.cma -I otherlibs/win32unix unix.cma -I lib -I lib/stublibs lib/camlp4/camlp4lib.cma -linkall lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParser.cmo lib/camlp4/Camlp4Parsers/Camlp4OCamlRevisedParserParser.cmo lib/camlp4/Camlp4Printers/Camlp4AutoPrinter.cmo   lib/camlp4/Camlp4Bin.cmo -o bin/camlp4r.exe 

rem   camlp4boot.exe	camlp4o.exe   camlp4oof.exe  camlp4rf.exe
rem   camlp4.exe	camlp4of.exe  camlp4orf.exe  camlp4r.exe

rem   rm -f lib/camlp4/Camlp4.cmo lib/camlp4/Camlp4_config.cmo lib/camlp4/Camlp4_import.cmo
rem   rm -f lib/camlp4/boot/Camlp4_import.cmo lib/camlp4/boot/Camlp4_config.cmo lib/camlp4/boot/Camlp4.cmo lib/camlp4/boot/camlp4boot.cmo
