#define OCAML_VERSION_MAJOR 4
#define OCAML_VERSION_MINOR 1
#define OCAML_VERSION_PATCHLEVEL 0
#define OCAML_VERSION_ADDITIONAL "ocp1"
#define OCAML_VERSION 40100
#define OCAML_VERSION_STRING "4.01.0+ocp1"
